FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build
FROM alpine:latest
COPY --from=builder /app/dist /app/dist
CMD ["sh", "-c", "rm -rf /output/* && cp -r /app/dist/. /output/"]