# Generated by Django 6.0.6 on 2026-06-04 20:53

import comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(max_length=100, validators=[comments.models.validate_user_name]),
        ),
    ]
