# Generated by Django 6.0.6 on 2026-06-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='homepage',
            field=models.URLField(blank=True, default=''),
        ),
    ]
